version: '3'

services:

  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres'
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vueapi
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  #  start mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      # smtp port listening for mail comming in
      - "1025:1025" 
      # web interface to check email
      - "8025:8025"
    restart: always
